//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyCommunityCenter.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        public int ToDoId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsComplete { get; set; }
        public int ToDoListID { get; set; }
    
        public virtual ToDoList ToDoList { get; set; }
    }
}
